### ISSUE TITLE
Co-working session agenda: 2022-01-17

### ISSUE THREAD

**Issue by lwjohnst86** [science-collective/admin#3]
# Description

This is a largely asynchronous co-working session, though we will kick things off at a designated time (start of the calendar invite). You can work for as long (or as short) as you'd like or are able. No pressure and no expectations :relaxed: 

# Agenda

## Tasks to do before session

- [x] Add your username to [the Google Forms](https://forms.gle/RuV7knjaaycXECk4A) survey so I can add you to this organization.
- [x] Agree on potential project in https://github.com/science-collective/admin/issues/2.
- [x] Decide on which project to work on, either: https://github.com/science-collective/admin/issues/5 or https://github.com/science-collective/admin/issues/6
- [x] Fill in time for next meeting: http://whenisgood.net/74ab4t4

## During session

- [x] Comment on the Issue about Discord if you have thoughts: https://github.com/science-collective/admin/issues/4
- [x] Work on the tasks within each project issue tracker. Write a comment in the project issue about what task you would like to work on.
    - Scoping Review: https://github.com/science-collective/admin/issues/5
    - R Package: https://github.com/science-collective/admin/issues/6

**Comment by hchats** [comment]
Hi Luke :) Are we planning to meet face-to-face in Aarhus for this one?

**Comment by lwjohnst86** [comment]
No, this will be virtual. I'll add the links eventually and send updates to the calendar event :relaxed:

**Comment by hchats** [comment]
> No, this will be virtual. I'll add the links eventually and send updates to the calendar event ☺️

Okay! I have an appointment at 14:30 but will be present otherwise!
